/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import com.mycompany.biblioteca.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mario
 */
public class hacercompra extends javax.swing.JFrame {

    /**
     * Creates new form hacercompra
     */
    
    Conexion con1=new Conexion();
    Connection conet;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int idc;
    
    public hacercompra(ArrayList <hacercompra> aHc) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        
        int at = 0;
        at= (int) (Math.random() * 10 + 1);
        tfempleado.setText(Integer.toString(at));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfcodigocliente = new javax.swing.JTextField();
        lbcodigo = new javax.swing.JLabel();
        lbnombre = new javax.swing.JLabel();
        tfcodigolibro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbnombre1 = new javax.swing.JLabel();
        tfempleado = new javax.swing.JTextField();
        btRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel1.setText("COMPRA");

        lbcodigo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        lbcodigo.setText("Ingresa el Codigo del Libro:");

        lbnombre.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        lbnombre.setText("Ingresa tu Codigo de Cliente:");

        tfcodigolibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodigolibroActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/carrito-de-compras.png"))); // NOI18N
        jButton1.setText("Comprar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbnombre1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        lbnombre1.setText("Codigo del Empleado que lo Atiende:");

        tfempleado.setEditable(false);
        tfempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfempleadoActionPerformed(evt);
            }
        });

        btRegresar.setBackground(new java.awt.Color(153, 153, 153));
        btRegresar.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        btRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/deshacer.png"))); // NOI18N
        btRegresar.setText("Regresar");
        btRegresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbcodigo)
                            .addComponent(lbnombre))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfcodigocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcodigolibro, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(lbnombre1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcodigolibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcodigo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnombre)
                    .addComponent(tfcodigocliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnombre1)
                    .addComponent(tfempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRegresar))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Agregar();
        nuevo();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfempleadoActionPerformed

    private void tfcodigolibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodigolibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodigolibroActionPerformed

    private void btRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btRegresarActionPerformed
    
    void Agregar(){
    try{
        if (tfcodigolibro.getText().equals("")||tfcodigocliente.getText().equals("")||tfempleado.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"ERROR: Campos Vacios");
        } else {
            String sql="insert into facturas(CodLibros, CodClientes, CodEmpleados) values ('"+tfcodigolibro.getText()+"','"+tfcodigocliente.getText()+"','"+tfempleado.getText()+"')";
            conet=con1.getConnection();
            st=conet.createStatement();
            st.executeUpdate(sql);
            
            
            JOptionPane.showMessageDialog(null,"Gracias por tu Compra !!!");
        }
        } catch (SQLException ex) {
            if(ex.getErrorCode()==1452){
                JOptionPane.showMessageDialog(null,"ERROR Codigo del Libro y/o Cliente NO Existe");
}
        }
}

void nuevo(){
            tfcodigolibro.setText("");
            tfcodigocliente.setText("");
            tfcodigolibro.requestFocus();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbnombre1;
    private javax.swing.JTextField tfcodigocliente;
    private javax.swing.JTextField tfcodigolibro;
    private javax.swing.JTextField tfempleado;
    // End of variables declaration//GEN-END:variables
}
