/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.util.ArrayList;

/**
 *
 * @author mario
 */
public class Menu extends javax.swing.JFrame {   
        ArrayList <Reporte> aReporte=new ArrayList<Reporte>();
        ArrayList <proveedores> aproveedores=new ArrayList<proveedores>();
        ArrayList <librosvent> alibros=new ArrayList<librosvent>();
        ArrayList <clientesvent> acliente=new ArrayList<clientesvent>();
        ArrayList <buscarvent> abuscar=new ArrayList<buscarvent>();
        ArrayList <empleadovent> aempleado=new ArrayList<empleadovent>();
        ArrayList <autorvent> aautorv=new ArrayList<autorvent>();
        ArrayList <categoriavent> acatv=new ArrayList<categoriavent>();
        ArrayList <repfacturacion> afacturacion=new ArrayList<repfacturacion>();


    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jColorChooser1 = new javax.swing.JColorChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btfacturacion = new javax.swing.JButton();
        btproveedor = new javax.swing.JButton();
        btlibro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btempleados = new javax.swing.JButton();
        btfacturas = new javax.swing.JButton();
        btautor = new javax.swing.JButton();
        btcategoria = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btbuscarp = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnopciones = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pila-de-libros-de-tres.png"))); // NOI18N
        jLabel1.setText("BIBLIOTECA  VIRTUAL");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("OTROS"));

        btfacturacion.setBackground(new java.awt.Color(153, 153, 153));
        btfacturacion.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        btfacturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salida_1.png"))); // NOI18N
        btfacturacion.setText("Salir");
        btfacturacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btfacturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btfacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfacturacionActionPerformed(evt);
            }
        });

        btproveedor.setBackground(new java.awt.Color(153, 153, 153));
        btproveedor.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        btproveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/persona-munequita.png"))); // NOI18N
        btproveedor.setText("Proveedores");
        btproveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btproveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btproveedorActionPerformed(evt);
            }
        });

        btlibro.setBackground(new java.awt.Color(153, 153, 153));
        btlibro.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        btlibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/libro-cubierta-abierta.png"))); // NOI18N
        btlibro.setText("LIBROS");
        btlibro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btlibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlibroActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/agregar-usuario_1.png"))); // NOI18N
        jButton1.setText("Clientes");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btempleados.setBackground(new java.awt.Color(153, 153, 153));
        btempleados.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        btempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/encuesta-de-personas_1.png"))); // NOI18N
        btempleados.setText("Empleados");
        btempleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btempleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btempleadosActionPerformed(evt);
            }
        });

        btfacturas.setBackground(new java.awt.Color(153, 153, 153));
        btfacturas.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        btfacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/archivar-factura.png"))); // NOI18N
        btfacturas.setText("Facturacion");
        btfacturas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btfacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btfacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfacturasActionPerformed(evt);
            }
        });

        btautor.setBackground(new java.awt.Color(153, 153, 153));
        btautor.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        btautor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lector-de-libros-abiertos.png"))); // NOI18N
        btautor.setText("Autor");
        btautor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btautor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btautorActionPerformed(evt);
            }
        });

        btcategoria.setBackground(new java.awt.Color(153, 153, 153));
        btcategoria.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        btcategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/fuente-del-libro.png"))); // NOI18N
        btcategoria.setText("Categoria");
        btcategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btautor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btcategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btfacturas, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btempleados, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(btfacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btempleados, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(btlibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btproveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btcategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btautor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btfacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btfacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("BUSQUEDAS"));

        btbuscarp.setBackground(new java.awt.Color(153, 153, 153));
        btbuscarp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btbuscarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/busqueda.png"))); // NOI18N
        btbuscarp.setText("BUSCAR");
        btbuscarp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btbuscarp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btbuscarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btbuscarp, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btbuscarp, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );

        mnopciones.setText("Opciones");
        jMenuBar1.add(mnopciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btproveedorActionPerformed
        // TODO add your handling code here:
        proveedores vproveedores=new proveedores(aproveedores);
    }//GEN-LAST:event_btproveedorActionPerformed

    private void btlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlibroActionPerformed
        // TODO add your handling code here:
        librosvent vlibros=new librosvent(alibros);
    }//GEN-LAST:event_btlibroActionPerformed

    private void btfacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfacturacionActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btfacturacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clientesvent vCliente=new clientesvent(acliente);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btbuscarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarpActionPerformed
        // TODO add your handling code here:
        buscarvent vBuscar=new buscarvent(abuscar);
    }//GEN-LAST:event_btbuscarpActionPerformed

    private void btautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btautorActionPerformed
        // TODO add your handling code here:
        autorvent vAutorv=new autorvent(aautorv);
    }//GEN-LAST:event_btautorActionPerformed

    private void btempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btempleadosActionPerformed
        // TODO add your handling code here:
        empleadovent vEmpleado=new empleadovent(aempleado);
    }//GEN-LAST:event_btempleadosActionPerformed

    private void btcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcategoriaActionPerformed
        // TODO add your handling code here:
        categoriavent vCategoria=new categoriavent(acatv);
    }//GEN-LAST:event_btcategoriaActionPerformed

    private void btfacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfacturasActionPerformed
        // TODO add your handling code here:
        repfacturacion vFactura=new repfacturacion(afacturacion);
    }//GEN-LAST:event_btfacturasActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btautor;
    private javax.swing.JButton btbuscarp;
    private javax.swing.JButton btcategoria;
    private javax.swing.JButton btempleados;
    private javax.swing.JButton btfacturacion;
    private javax.swing.JButton btfacturas;
    private javax.swing.JButton btlibro;
    private javax.swing.JButton btproveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenu mnopciones;
    // End of variables declaration//GEN-END:variables
}
